Repository dang-der/Dangder-server, pull requests merged in 2022-10, with the labels that each got.

#10 :camera_flash: [Merge] Add : 2주차 작업내용
  src/apis/dogs/dogs.resolver.ts
  src/apis/dogs/dogs.service.ts
  src/apis/dogs/entities/dog.entity.ts
  src/apis/interests/dto/createInterest.input.ts
  src/apis/interests/dto/interestCategory.output.ts
  src/apis/interests/entities/interest.entity.ts
  src/apis/interests/interests.resolver.ts
  src/apis/interests/interests.service.ts
Labels: 🐛 Bug, 🧩 Feature, 🔀 Merge_develop

#16 📸 : [Merge] blockUser 관련
  src/apis/blockUsers/blockUsers.module.ts
  src/apis/blockUsers/blockUsers.resolver.ts
  src/apis/blockUsers/blockUsers.service.ts
  src/apis/blockUsers/dto/createBlockUser.input.ts
  src/apis/blockUsers/entities/blockUser.entity.ts
  src/apis/passTickets/passTickets.service.ts
  src/apis/users/entities/user.entity.ts
  src/apis/users/users.resolver.ts
  src/apis/users/users.service.ts
Labels: 🧩 Feature, 🔀 Merge_develop

#18 📸 [Merge] Review Entity 추가 및 CRUD(작성중)
  src/apis/dogs/dogs.resolver.ts
  src/apis/dogs/dogs.service.ts
  src/apis/dogs/entities/dog.entity.ts
  src/apis/reviews/dto/createReview.input.ts
  src/apis/reviews/dto/updateReview.input.ts
  src/apis/reviews/entities/review.entity.ts
  src/apis/reviews/reviews.module.ts
  src/apis/reviews/reviews.resolver.ts
  src/apis/reviews/reviews.service.ts
Labels: 🔀 Merge_develop

#17 :camera_flash: [Merge] findUserAndDog -> 등록된 강아지 없을 시의 예외처리
  src/apis/users/users.service.ts
Labels: 🔀 Merge_develop

#23 :camera_flash: [Merge] 221026 Review entity명 수정
  src/apis/dogs/entities/dog.entity.ts
  src/apis/reviews/dto/createReview.input.ts
  src/apis/reviews/dto/updateReview.input.ts
  src/apis/reviews/entities/review.entity.ts
  src/apis/reviews/reviews.module.ts
  src/apis/reviews/reviews.resolver.ts
  src/apis/reviews/reviews.service.ts
Labels: 🔀 Merge_develop

#22 📸 [Merge] entity 수정/ blockUser/ report
  src/apis/blockUsers/blockUsers.resolver.ts
  src/apis/blockUsers/blockUsers.service.ts
  src/apis/blockUsers/dto/createBlockUser.input.ts
  src/apis/blockUsers/dto/updateBlockUser.input.ts
  src/apis/blockUsers/entities/blockUser.entity.ts
  src/apis/passTickets/entities/passTicket.entity.ts
  src/apis/payments/entities/payment.entity.ts
  src/apis/reports/dto/createReport.input.ts
  src/apis/reports/entities/report.entity.ts
  src/apis/reports/reports.module.ts
  src/apis/reports/reports.resolver.ts
  src/apis/reports/reports.service.ts
  src/apis/users/entities/user.entity.ts
Labels: 🔀 Merge_develop

#20 :camera_flash: [Merge] InterestChatRoom, Message CRUD 추가 및 fetchSocialLoginUser 추가
  src/apis/interestChatMessages/entities/interestChatMessage.entity.ts
  src/apis/interestChatMessages/interestChatMessages.module.ts
  src/apis/interestChatMessages/interestChatMessages.resolver.ts
  src/apis/interestChatMessages/interestChatMessages.service.ts
  src/apis/interestChatRooms/entities/interestChatRoom.entity.ts
  src/apis/interestChatRooms/interestChatRooms.module.ts
  src/apis/interestChatRooms/interestChatRooms.resolver.ts
  src/apis/interestChatRooms/interestChatRooms.service.ts
  src/apis/interests/entities/interest.entity.ts
  src/apis/interests/interests.resolver.ts
  src/apis/users/users.resolver.ts
  src/app.module.ts
Labels: 🧩 Feature, 🔀 Merge_develop, ⚙️ Refactor

#24 📸 [Merge] report / block 관련 기능 구현
  src/apis/blockUsers/blockUsers.service.ts
  src/apis/blockUsers/entities/blockUser.entity.ts
  src/apis/reports/dto/createReport.input.ts
  src/apis/reports/reports.module.ts
  src/apis/reports/reports.resolver.ts
  src/apis/reports/reports.service.ts
  src/apis/users/users.service.ts
Labels: 🔀 Merge_develop

#27 :fire: 221026 - refactor : Stop유저 로그인차단 등
  src/apis/auths/auths.resolver.ts
  src/apis/interestChatRooms/entities/interestChatRoom.entity.ts
  src/apis/interests/dto/interestCategory.output.ts
  src/apis/interests/entities/interest.entity.ts
  src/apis/interests/interests.resolver.ts
  src/apis/interests/interests.service.ts
  src/gateways/chat/chat.gateway.ts
  src/gateways/chat/chat.service.ts
Labels: 🔥 Hotfix, 🔀 Merge_develop

#28 📸 Refactor : createReview수정, fetchReviews 추가
  src/apis/dogs/entities/dog.entity.ts
  src/apis/reviewDetails/entities/reviewDetail.entity.ts
  src/apis/reviews/dto/createReview.input.ts
  src/apis/reviews/entities/review.entity.ts
  src/apis/reviews/reviews.module.ts
  src/apis/reviews/reviews.resolver.ts
  src/apis/reviews/reviews.service.ts
Labels: 🐛 Bug, 🧩 Feature, 🔀 Merge_develop

#29 📸 Hotfix : review relation 추가
  src/apis/reviews/reviews.service.ts
Labels: 🔥 Hotfix

#30 📸 Hotfix : review relation 추가2
  src/apis/reviews/reviews.service.ts
Labels: 🔥 Hotfix, 🔀 Merge_develop

#31 📸 Refactor : fetchReceiveReviews 에 이미지조회 추가
  src/apis/reviews/reviews.service.ts
Labels: 🧩 Feature, 🔥 Hotfix, 🔀 Merge_develop
