Repository dang-der/Dangder-server, pull requests merged in 2022-11, with the labels that each got.

#32 221030 - hotfix : 테스트용 createIChatMessage 생성
  src/apis/interestChatMessages/entities/interestChatMessage.entity.ts
  src/apis/interestChatMessages/interestChatMessages.resolver.ts
  src/apis/interestChatMessages/interestChatMessages.service.ts
Labels: 🔥 Hotfix, 🔀 Merge_develop

#36 :camera_flash: [Merge] joinIChatRoom 추가 및 Refactor
  src/apis/interestChatRooms/interestChatRooms.resolver.ts
  src/apis/interestChatRooms/interestChatRooms.service.ts
  src/apis/likes/likes.service.ts
  src/apis/passTickets/passTickets.resolver.ts
  src/apis/passTickets/passTickets.service.ts
Labels: 🧩 Feature, 🔥 Hotfix, 🔀 Merge_develop

#37 📸 [Merge] elasticsearch User
  elk/logstash/logstash-user.conf
  elk/logstash/logstash.conf
  elk/logstash/template-user.json
  src/apis/blockUsers/blockUsers.resolver.ts
  src/apis/blockUsers/blockUsers.service.ts
  src/apis/payments/payments.resolver.ts
  src/apis/payments/payments.service.ts
  src/apis/reports/reports.resolver.ts
  src/apis/reports/reports.service.ts
  src/apis/users/users.module.ts
  src/apis/users/users.resolver.ts
  src/apis/users/users.service.ts
Labels: 🧩 Feature, 🔀 Merge_develop

#38 📸 [Add] fetchAroundDogs 필터기능 추가 & fetchDogsBySearch 추가 (Elasticsearch)
  docker-compose.dev.yaml
  elk/logstash/logstash-dog.conf
  elk/logstash/template-dog.json
  src/apis/dogs/dogs.module.ts
  src/apis/dogs/dogs.resolver.ts
  src/apis/dogs/dogs.service.ts
Labels: 🔥 Hotfix, 🔀 Merge_develop

#42 📸 [Refactor] elasticksearch 수정, fetchAllReviews 추가
  src/apis/dogs/dogs.resolver.ts
  src/apis/dogs/dogs.service.ts
  src/apis/dogs/dto/dogElasticsearch.output.ts
  src/apis/reviews/reviews.resolver.ts
  src/apis/reviews/reviews.service.ts
Labels: 🐛 Bug, 🔥 Hotfix, 🔀 Merge_develop

#43 📸 [Merge] elasticsearch - user 마무리, admin page fetch 시리즈 수정
  elk/logstash/logstash-user.conf
  elk/logstash/template-user.json
  src/apis/auths/auths.module.ts
  src/apis/blockUsers/blockUsers.resolver.ts
  src/apis/blockUsers/blockUsers.service.ts
  src/apis/blockUsers/dto/blockUserOutput.ts
  src/apis/blockUsers/entities/blockUser.entity.ts
  src/apis/payments/dto/paymentOutput.ts
  src/apis/payments/entities/payment.entity.ts
  src/apis/payments/payments.module.ts
  src/apis/payments/payments.resolver.ts
  src/apis/payments/payments.service.ts
  src/apis/reports/dto/reportOutput.ts
  src/apis/reports/entities/report.entity.ts
  src/apis/reports/reports.module.ts
  src/apis/reports/reports.resolver.ts
  src/apis/reports/reports.service.ts
  src/apis/users/dto/userElasticsearch.output.ts
  src/apis/users/users.resolver.ts
  src/apis/users/users.service.ts
Labels: 🧩 Feature, 🔀 Merge_develop

#45 📸 [Merge] fetchDogsBySearch에서 deletedAt 수정
  src/apis/dogs/dogs.service.ts
  src/apis/dogs/entities/dog.entity.ts
Labels: 🐛 Bug, 🔀 Merge_develop

#46 📸 [Merge] fetch series 수정
  elk/logstash/logstash-user.conf
  src/apis/blockUsers/blockUsers.resolver.ts
  src/apis/blockUsers/blockUsers.service.ts
  src/apis/blockUsers/entities/blockUser.entity.ts
  src/apis/payments/payments.resolver.ts
  src/apis/payments/payments.service.ts
  src/apis/reports/entities/report.entity.ts
  src/apis/reports/reports.resolver.ts
  src/apis/reports/reports.service.ts
  src/apis/users/dto/userElasticsearch.output.ts
  src/apis/users/users.service.ts
Labels: 🐛 Bug, 🔀 Merge_develop
